version: 2
aliases:
- &ssh-fingerprint
    fingerprints:
      - "ae:83:a5:6c:93:c9:16:57:ec:21:b9:6f:9c:5a:10:9c"
- &install-dependencies
  name: Install Node Dependencies
  command: npm install
- &test
  name: Test
  command: npm run test
- &build
  name: Build
  command: npm run build
- &GCP-auth
  name: GCP Authenticate
  command: |
    echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
    /tools/gcp_authenticate.sh
- &docker-login
  name: Docker login
  command: |
    docker login -u _json_key --password-stdin https://eu.gcr.io <<< "${DOCKER_PASSWORD}"
- &docker-build-and-push
  name: Docker build and push
  command: |
    IMAGE="eu.gcr.io/entur-system-1287/${CIRCLE_PROJECT_REPONAME}"
    echo "Image: ${IMAGE}"
    docker build -t $IMAGE .
    docker tag $IMAGE "${IMAGE}":"${CIRCLE_SHA1}"
    docker push $IMAGE
- &save-dependency-cache
  paths:
  - node_modules
  key: node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
- &restore-dependency-cache
  name: Restore dependency cache
  keys:
  - node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
- &post-hook
  name: Notify about build and docker image pushed
  command: |
    echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
    echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
    echo 'export BUILD_STATUS_API_KEY="$BUILD_STATUS_API_KEY"' >> $BASH_ENV
    /tools/build_notify.sh
jobs:
  install:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    steps:
    - checkout
    - run: *install-dependencies
    - save-cache: *save-dependency-cache
  test-build:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    steps:
    - checkout
    - restore-cache: *restore-dependency-cache
    - run: *build
  test:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    steps:
    - checkout
    - restore-cache: *restore-dependency-cache
    - run: *test
  build:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    steps:
    - checkout
    - restore-cache: *restore-dependency-cache
    - run: *build
    - run: *GCP-auth
    - setup_remote_docker:
        docker_layer_caching: true
    - run: *docker-login
    - run: *docker-build-and-push
    - run: *post-hook
workflows:
  version: 2
  install-test-build-deploy:
    jobs:
    - install:
        context: org-carbon
    - test-build:
        context: org-carbon
        requires:
        - install
        filters:
          branches:
            ignore:
            - master
    - test:
        context: org-carbon
        requires:
        - install
    - build:
        context: org-carbon
        requires:
        - test
        filters:
          branches:
            only:
            - master
