enum FLEXIBLE_LINE_STEP {
  ABOUT = 'stepperAbout',
  JOURNEYPATTERN = 'stepperJourneyPattern',
  SERVICEJOURNEY = 'stepperServiceJourney',
  BOOKING = 'stepperBooking',
}

export const FLEXIBLE_LINE_STEPS: FLEXIBLE_LINE_STEP[] = [
  FLEXIBLE_LINE_STEP.ABOUT,
  FLEXIBLE_LINE_STEP.JOURNEYPATTERN,
  FLEXIBLE_LINE_STEP.SERVICEJOURNEY,
  FLEXIBLE_LINE_STEP.BOOKING,
];
