name: Production maintenance mode
on: workflow_dispatch
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - uses: actions/checkout@v5
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Copy maintenance mode file
        run: mkdir build && cp .github/maintenance/index.html build/index.html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENT_ENKI_PRD }}'
          channelId: live
          projectId: ent-enki-prd
